<h1 style = 'color:red'><b>Week-8b, Numpy Basic Assignment</b><h1>

Name - Gorachanda Dash <br>
Date - 26 Feb 2023 <br>
Week 9, Numpy Basic Assignment

Consider the below code to answer further questions:

import numpy as np<br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]<br>
array_list = np.array(object = list_)

In [10]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

<p style=" color : #4233FF"><b>Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.</b></p>

Yes, there is a difference in the data type of the variables list_ and array_list. The variable list_ is a Python list, while the variable array_list is a NumPy array.

In [11]:
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


<p style=" color : #4233FF"><b>Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.</b></p>

In [12]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in np.nditer(array_list):
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


<p style=" color : #4233FF"><b>Q3. Considering the following changes in the variable, array_list:</b>

```python
array_list = np.array(object = list_, dtype = int)
```
- Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_and array_list.
</p>

Yes, there will be a difference in the data type of the elements present in list_ and array_list after specifying dtype=int when creating array_list. The elements in array_list will be converted to the integer data type.

In [13]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Consider the below code to answer further questions:
```python
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
```

In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

<p style=" color : #4233FF"><b>Q4. Write a code to find the following characteristics of variable, num_array:</b>

(i) shape<br>
(ii) size<br></p>

In [15]:
print('shape', num_array.shape)
print('size', num_array.size)

shape (2, 3)
size 6


<p style=" color : #4233FF"><b>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.</b><br>

[Hint: The size of the array will be 9 and the shape will be (3,3).]</p>

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<p style=" color : #4233FF"><b>Q6. Create an identity matrix of shape (5,5) using numpy functions?</b><br>

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]</p>

In [22]:
np.eye(5,k=0,dtype=int,)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])


<h1 style = 'color:orange'>
    <b><div>THANK YOU</div></b>
</h1>
